[project]
name = "scietex.modbus_service"
description = "Scietex microservice daemon for MODBUS communication"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [{ name = "Anton Bondarenko", email = "bond.anton@gmail.com" }]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]
dependencies = [
  "scietex.hal.serial>=2.0.0",
  "scietex.service[valkey]~=5.2.0",
]
dynamic = ["version"]

[project.urls]
"Bug Tracker" = "https://github.com/bond-anton/scietex.modbus_service/issues"
"Homepage" = "https://github.com/bond-anton/scietex.modbus_service"

[project.scripts]
start-modbus-service = "scietex.modbus_service.run_worker:main"

[project.optional-dependencies]
dev = ["tox>=4.45.0"]
lint = ["ruff", "ty"]
test = ["pytest", "pytest-asyncio"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.setuptools.dynamic]
version = { attr = "scietex.modbus_service.version.__version__" }

[tool.setuptools.package-data]
"scietex.modbus_service" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]
