"""Tasks enums."""

from enum import Enum


class Tasks(Enum):
    """Modbus worker tasks."""

    CONFIGURATION_READ = "CONFIGURATION READ"
    MODBUS_DISCONNECT = "MODBUS DISCONNECT"
    MODBUS_CONNECT = "MODBUS CONNECT"
    MODBUS_MONITOR = "MODBUS MONITOR"

    DEVICES_DISCONNECT = "DEVICES DISCONNECT"
    DEVICES_CONNECT = "DEVICES CONNECT"

    DEVICE_DISCONNECT = "DEVICE DISCONNECT"
    DEVICE_CONNECT = "DEVICE CONNECT"
    DEVICE_MONITOR = "DEVICE MONITOR"
    DEVICE_DISABLE = "DEVICE DISABLE"
    DEVICE_ENABLE = "DEVICE ENABLE"
